services:
  zombie-hunter:
    tty: true
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - type: bind
        source: ../
        target: /zombie-hunter
    command: [ "bash" ]
